name: Build and Release Windows App

on:
  workflow_dispatch: # فقط با دکمه دستی اجرا میشه

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # دسترسی برای ساخت خودکار تگ و ریلیز

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Desktop & Create Platform Files
        run: |
          flutter config --enable-windows-desktop
          flutter create --platforms=windows .

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Archive Release Folder
        shell: pwsh
        run: |
          $source = "build\windows\x64\runner\Release"
          $dest = "AdvancedCalculator_Windows.zip"
          Compress-Archive -Path "$source\*" -DestinationPath $dest

      - name: Create Tag and Release Automatically
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0 # خودش این تگ را می‌سازد
          name: Release v1.0.0
          files: AdvancedCalculator_Windows.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
