name: Build and Release Windows App

on:
  push:
    tags:
      - 'v*' # هر زمان که تگی با پیشوند v (مثل v1.0.0) زدید، اکشن خودکار ران می‌شود
  workflow_dispatch: # این خط دکمه دستی برای اجرای اکشن را اضافه می‌کند

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Archive Release Folder
        shell: pwsh
        run: |
          # مسیر خروجی بیلد ویندوز
          $source = "build\windows\x64\runner\Release"
          # نام فایل زیپ خروجی
          $dest = "AdvancedCalculator_Windows.zip"
          Compress-Archive -Path "$source\*" -DestinationPath $dest

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: AdvancedCalculator_Windows.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
